version: 2
jobs:
  test:
    working_directory: ~
    docker:
      - image: ${TOOLS_IMAGE:-themuse/tools:latest}
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: true
      - run:
          name: Lint Terraform Files
          command: terraform fmt -check=true -list=true -diff=true